export default function Articles() {
  return (
    <div className="p-4 text-text">
      <h1 className="text-2xl font-bold">artpage</h1>
      <p className="text-justify"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis odio ex, auctor a sapien id, ultrices tincidunt erat. Curabitur sed suscipit nulla. Integer eget ante diam. Vestibulum feugiat quam eu elit efficitur congue. Suspendisse non justo vel tellus maximus ullamcorper. Vivamus dictum pellentesque sollicitudin. Aliquam id mi sed magna scelerisque vulputate. Curabitur suscipit sem at libero lacinia pellentesque. Phasellus quis nisl vulputate, consequat nisl eleifend, mollis massa.
        Curabitur quis est sollicitudin, porta diam ut, cursus nunc. Donec eu arcu varius, sodales mauris nec, fermentum diam. In hac habitasse platea dictumst. Nullam vel maximus tortor, maximus aliquet velit. Duis tristique vehicula tellus in ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vitae orci ornare dolor pellentesque tristique nec sed eros. Nullam sodales lacinia nunc, in fermentum justo. Aliquam et neque faucibus, pulvinar ex a, convallis metus.
        Mauris in mauris vitae sem condimentum blandit. Sed malesuada accumsan iaculis. Nunc dui lacus, euismod at malesuada quis, iaculis nec velit. Maecenas in dui in diam vehicula viverra sit amet in leo. Nulla et nisi in nibh vestibulum malesuada a quis ante. Aenean interdum metus sit amet leo lacinia auctor. Ut vulputate efficitur nulla eget fringilla. Aenean non mauris at urna egestas porttitor quis vitae est. Donec viverra ac orci sed pulvinar. Vestibulum elementum egestas rhoncus. Integer euismod tincidunt quam, non sagittis urna faucibus eget. Vivamus quis purus dui. Curabitur egestas magna sit amet mauris facilisis, a blandit augue tempor. In sed vehicula nisi.
        Nunc porta nulla magna, quis lobortis tellus tristique vel. Vestibulum tristique neque enim, eget tristique nulla aliquam in. Vestibulum consectetur est rhoncus, ultricies sem eget, pellentesque lacus. Ut rutrum auctor mauris, sit amet fermentum velit. Aliquam ac vulputate nibh, vehicula laoreet massa. Donec ac vestibulum urna. Vivamus pretium imperdiet bibendum. Donec finibus ultricies mollis. Donec eu viverra nulla. Nulla aliquet quis libero ut ornare. Aenean volutpat porttitor eros. Duis in maximus ex. Mauris laoreet a sapien et tristique. Phasellus lobortis feugiat mi, nec porttitor massa mattis vel.
        Donec in interdum leo. Etiam quis mauris commodo, tempus turpis gravida, fermentum dui. Mauris felis nisl, iaculis ut aliquam ac, sagittis in velit. Nunc malesuada est a mauris interdum volutpat. Aliquam euismod feugiat purus, aliquam consectetur arcu. Mauris dignissim blandit urna sed fermentum. Maecenas tincidunt enim in mattis pulvinar.
        Phasellus dignissim risus venenatis risus dictum sagittis. Nulla facilisi. Sed iaculis et quam non laoreet. Vestibulum in ultricies metus. Pellentesque venenatis augue sit amet turpis porttitor tincidunt. Cras vitae scelerisque libero. Morbi scelerisque justo vitae erat efficitur, in dignissim metus condimentum. Curabitur sapien ipsum, fermentum vitae nisi non, dignissim interdum sem. Nullam eget tincidunt nisi. Phasellus egestas, mi at mattis fringilla, ante mauris hendrerit leo, et accumsan est ante id diam. Nam semper justo et eros imperdiet, id faucibus ex auctor. Integer elementum rhoncus rutrum. Nunc auctor urna sed ipsum tempus pretium.
        Sed mollis, nisl et vehicula sollicitudin, orci lectus dictum elit, vel ultricies ipsum ante egestas neque. In a turpis tortor. Nam sit amet ipsum eget quam egestas pharetra. Nullam tempus bibendum pharetra. Morbi feugiat, odio id luctus ullamcorper, tortor lorem luctus leo, eget aliquam risus orci eget lacus. Phasellus id nulla vitae diam tincidunt tempus vel hendrerit leo. Etiam dignissim convallis urna, vel vestibulum urna tempor nec. Vestibulum ac turpis purus. Etiam sit amet sem vel nisl consequat vulputate. Nulla ultrices fermentum mi, vel convallis risus congue quis.
        Nam sollicitudin velit et risus congue, tristique lobortis ipsum congue. Donec vitae ante elementum, dapibus nulla interdum, dapibus nisi. Vestibulum varius libero non ex lacinia tristique. Vivamus sed orci interdum, tincidunt augue lobortis, volutpat erat. Vivamus nec feugiat quam. Proin sit amet posuere augue. Pellentesque pharetra facilisis ultricies. Phasellus vehicula pretium urna quis eleifend. Mauris cursus porta ligula, a aliquam orci lacinia nec. Etiam porttitor vel nulla eget cursus. Sed bibendum felis vitae pretium maximus. Sed dignissim cursus lacus, ut consequat eros tincidunt id. Sed at dui vel turpis finibus malesuada. Praesent ac elit vitae erat iaculis commodo sit amet nec ante. Morbi vitae scelerisque metus. Maecenas nec nulla est.
        Nullam molestie elit a purus lacinia fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec venenatis arcu. Sed non nibh imperdiet, mollis lorem vitae, ornare mauris. Vestibulum commodo bibendum felis, eu bibendum tellus mattis ut. Fusce est dui, tempor at urna sed, luctus gravida odio. Fusce molestie, odio at dapibus suscipit, felis diam bibendum leo, ac tincidunt nibh ante in dolor. Sed vel enim consectetur, consequat augue ac, rhoncus turpis. Vivamus in magna eget libero euismod commodo in sit amet neque. Vestibulum tempor blandit ante. Nam pellentesque purus eu nunc ornare fermentum. Morbi in sapien non enim faucibus eleifend. Sed ullamcorper felis vitae fermentum convallis.
        Nam id consectetur neque. Donec tempor est a erat sodales, in semper lectus sagittis. Cras in risus in lorem ultrices tristique et id augue. Vestibulum sed velit dignissim purus malesuada dapibus. Sed egestas bibendum nibh in blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis tristique justo a facilisis imperdiet.
        Cras ac est sem. Nulla non ligula sed sem vestibulum mollis a at quam. Vivamus vel orci est. Integer ut viverra elit, in bibendum nulla. Ut ac sapien bibendum, ornare dolor ac, porttitor leo. Quisque neque felis, tincidunt vitae aliquam et, bibendum in nibh. Aliquam pretium sagittis risus at tincidunt. Nullam id quam mollis, molestie elit vel, lacinia urna. In elit ipsum, molestie in nunc commodo, blandit elementum mi. Sed gravida scelerisque tempus.
        Morbi tempor tellus ac viverra volutpat. Aenean at odio eget odio fermentum dictum at sit amet felis. Sed lacus risus, aliquam eget odio quis, pulvinar bibendum risus. Integer condimentum elit in dui congue finibus. Suspendisse vitae auctor mi. Phasellus at massa commodo, pulvinar magna quis, dapibus eros. Mauris sapien quam, convallis vel accumsan eget, lobortis at leo. Nullam eu pellentesque quam, nec bibendum libero.
        Suspendisse potenti. Suspendisse lacus enim, hendrerit nec leo ut, pretium rutrum tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin id tristique quam. Suspendisse tempor sapien in porta scelerisque. Suspendisse potenti. Vivamus et urna sit amet lacus lacinia aliquet. Pellentesque ac magna imperdiet, pulvinar nibh vitae, congue erat. Aliquam erat volutpat. Quisque tristique porta tempus. Nullam in sollicitudin magna. Nunc iaculis porttitor sodales. Donec nisi tortor, lobortis mattis convallis sit amet, pulvinar in magna.
        Vivamus lacinia mauris in massa tempus blandit. Proin mollis magna et tortor luctus dapibus. Vivamus ligula eros, feugiat eu leo a, rhoncus dignissim leo. Quisque fermentum, turpis quis molestie eleifend, mi est varius augue, in viverra erat tortor eu risus. Sed at erat sit amet magna hendrerit aliquam. Cras euismod neque et odio tristique viverra. Nam nisi augue, tincidunt non gravida ac, ultrices ut erat. Donec sollicitudin quam in dolor mollis, ut tempus metus pretium. Cras a auctor urna. Vivamus sagittis auctor nunc, sit amet gravida neque condimentum vitae. In varius malesuada metus, non hendrerit augue eleifend eu. Ut pellentesque consequat feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
        Ut eget tortor et ligula ultrices dignissim non sed turpis. Donec ultrices justo sed velit finibus, quis tempor lorem euismod. Nullam ut nulla urna. Integer blandit diam nunc, eget ultricies massa consequat non. Phasellus cursus, dui vel tempus venenatis, ipsum metus egestas mi, at rhoncus sapien mauris ut augue. Nulla ut risus sed turpis maximus suscipit volutpat non eros. Morbi sem felis, tincidunt sit amet nulla vitae, consequat venenatis nunc. In maximus turpis lorem, vitae luctus turpis vestibulum in. In sed elementum dui.
        Phasellus et condimentum arcu. Sed quis congue sapien. Morbi lacinia odio non felis hendrerit consequat. Fusce ac mauris magna. Phasellus consectetur sodales felis. Cras tempor mauris velit, ut consequat arcu iaculis sed. Sed ut sodales erat. Nunc tempor non sapien consectetur porttitor. Praesent ut ante aliquet, tempus nisl vel, porttitor risus. Curabitur rhoncus dui id ex vulputate, at placerat augue dictum. Nam sodales arcu non dignissim auctor. Etiam scelerisque at mauris et pretium. Donec eros massa, consectetur quis tellus sit amet, feugiat vehicula neque. Nullam malesuada semper elit, vitae posuere ante rhoncus in.
        Nulla varius pellentesque aliquam. In auctor nisl vel sodales blandit. Nulla iaculis faucibus sapien, id cursus enim imperdiet sed. Duis ornare tempus nunc, vel pellentesque tellus pulvinar et. Vestibulum sagittis fermentum sodales. Fusce elementum condimentum tellus, non mattis est consectetur faucibus. Duis pretium ante nec est euismod finibus. Donec venenatis ac tellus vel vulputate. Mauris luctus ante id eros feugiat, maximus rutrum tortor elementum. Maecenas tincidunt magna at velit blandit ullamcorper. Pellentesque suscipit suscipit libero at laoreet. Donec vitae justo ante. Praesent non malesuada risus. Etiam nec tortor sed nulla tincidunt tincidunt non nec mi.
        Quisque feugiat elit felis, et accumsan leo ornare non. Quisque et arcu ut libero tempus blandit id in risus. Sed quis elit nisl. Etiam accumsan ante ac justo mattis, eget bibendum lectus rutrum. Maecenas felis lectus, laoreet eu consequat at, rhoncus convallis erat. Quisque tempus vitae dolor at semper. Sed id magna posuere, laoreet leo eget, pretium diam. Curabitur posuere neque ac turpis sagittis maximus. Proin venenatis arcu tincidunt, vestibulum leo et, condimentum tellus. Ut eget vehicula lectus, id maximus diam. Integer ullamcorper, nisi consectetur efficitur ornare, massa lorem molestie lorem, quis sollicitudin ligula turpis eget mauris. Integer ultricies aliquet pharetra. Nunc diam ipsum, feugiat ac enim at, tincidunt lacinia ante. Aliquam a mattis velit.
        Cras rutrum, diam sed gravida tempus, enim justo blandit ligula, ac dictum elit nibh vulputate nisl. Integer commodo urna ac lacus mollis, sed lacinia leo facilisis. Maecenas vitae consectetur diam, a eleifend ante. Nullam fermentum lacus ac cursus tincidunt. Aliquam iaculis sapien mi, at molestie tellus rutrum eget. Sed ut molestie erat. Vivamus hendrerit ut massa vel fermentum. Quisque id placerat nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce sit amet ante pellentesque, euismod neque nec, sodales nisl. Morbi tincidunt enim ante.
      </p>

      <button className="fixed bottom-6 right-6 bg-accent text-white text-lg px-4 py-2 rounded-xl shadow-lg hover:bg-accent/90 transition-all"
        aria-label="Compose"
      >
        +
      </button>
    </div>
  );
}
